kind: pipeline
name: default

steps:

  - name: authenticate
    image: robertstettner/drone-mvn-auth
    pull: true
    settings:
      servers:
        from_secret: maven_servers

  - name: build
    image: gradle:jdk11
    commands:
      - gradle build -x test
    depends_on:
      - authenticate

  - name: test
    image: gradle:jdk11
    commands:
      - gradle build
    depends_on:
      - build

#  - name: sonarqube
#    image: gradle:jdk11
#    commands:
#      - mvn -X -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_PROJECTKEY sonar:sonar -P ssb-bip,coverage -Dmaven.javadoc.skip=true --batch-mode --global-settings settings.xml
#    environment:
#      SONAR_HOST_URL: https://sonarqube.prod-bip-ci.ssb.no
#      SONAR_PROJECTKEY:
#        from_secret: sonar_token
#      MAVEN_HOME: /drone/src/.m2
#      M2_HOME: /drone/src/.m2
#    depends_on:
#      - test

#  - name: publish-jar
#    image: maven:3-jdk-8
#    commands:
#      - mvn clean package deploy -P ssb-bip, -DskipTests=true -Djdk.tls.client.protocols="TLSv1.2" --batch-mode --global-settings settings.xml
#    when:
#      ref:
#        - refs/heads/develop
#        - refs/tags/*
#    environment:
#      MAVEN_HOME: /drone/src/.m2
#      M2_HOME: /drone/src/.m2
#    depends_on:
#      - sonarqube
#      - codacy
#      - codecov

  - name: publish-docker-zeppelin
    image: plugins/gcr
    settings:
      dockerfile: zeppelin-plugin/docker/Dockerfile
      repo: eu.gcr.io/prod-bip/ssb/dapla-zeppelin
      registry: eu.gcr.io
      auto_tag: true
      json_key:
        from_secret: gcr_credentials
    when:
      ref:
        - refs/heads/develop
        - refs/tags/*
    depends_on:
      - build

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_url
      channel: bip-ci-test
    when:
      status: [ success, failure ]
    depends_on:
      - build
      - publish-docker-zeppelin

---
kind: secret
name: maven_servers
get:
  path: drone-maven-servers
  name: ssb-bip-maven-servers

---
kind: secret
name: slack_webhook_url
get:
  path: drone-slack-webhook-url
  name: slack-webhook-url
---
kind: secret
name: sonar_host
get:
  path: drone-sonarqube-configuration
  name: url
---
kind: secret
name: sonar_token
get:
  path: drone-sonarqube-configuration
  name: token
---
kind: secret
name: gcr_credentials
get:
  path: drone-gcr-credentials
  name: gcr-credentials