micronaut:
  application:
    name: server

datasources:
  default:
    url: 'jdbc:postgresql://localhost:5432/'
    username: 'postgres'
    password: 'mysecretpassword'
    driverClassName: 'org.postgresql.Driver'
flyway:
  datasources:
    default:
      locations: classpath:dbmigrations
grpc:
  server:
    keep-alive-time: 3h
#    max-inbound-message-size: 1024
#    ssl:
#      cert-chain: 'ca.cert'
#      private-key: 'ca.key'